
MOTIVATIONS_LIST = [
        ('01', '01. Personnelle / Ne souhaite pas répondre'),
        ('02', '02. Etudes en France'),
        ('03', '03. Etudes au Canada'),
        ('04', '04. Etudes dans un autre pays'),
        ('05', '05. Intégration française'),
        ('06', '06. Carte de résident en France'),
        ('07', '07. Immigration au canada'),
        ('08', '08. Immigration au Quèbec'),
        ('09', '09. Immigration dans un autre pays'),
        ('10', '10. Naturalisation française'),
        ('11', '11. Naturalisation suisse'),
        ('12', '12. Citoyenneté canadienne'),
        ('13', '13. Autre demande de nationalité'),
        ('14', '14. Force Canadiennes'),
        ('15', '15. Métiers de la sécurité en France'),
        ('16', '16. Professions médicales au canada'),
        ('17', '17. Autre motivation professionnzllz'),
    ]